plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    testImplementation platform('org.springframework.boot:spring-boot-dependencies:4.1.0')

    implementation project(':shared')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}